package idir.embag.DataModels.Metadata;

public enum EEventDataKeys {
    FamilyCode,
    FamilyName,
    ArticleId,
    ArticleName,
    CodeBar,
    Quantity,
    Price,
    GroupId,
    GroupName,
    StartDate,
    EndDate,
    WorkerId,
    PriceShift,
    QuantityShift,
    Username,
    FullName,
    Email,
    Phone,
    Password,
    AttributeWrappersList,
    DialogContent,
    ProductInstance,
    SessionGroupInstance,
    SessionRecordInstance,
    SessionRecordList,
    ArticleCode,
    PanelId,
    Subscriber,

}
