package idir.embag.DataModels.Metadata;

/**
 * The keys used are the same as in the database columns.  
*/

public enum EEventDataKeys {
    FamilyCode,
    FamilyName,
    ArticleId,
    ArticleName,
    CodeBar,
    Quantity,
    Price,
    GroupId,
    GroupName,
    StartDate,
    EndDate,
    WorkerId,
    PriceShift,
    QuantityShift,
    Username,
    FullName,
    Email,
    Phone,
    Password,
    AttributeWrappersList,
    AttributeWrappersMap,
    DialogContent,
    ProductInstance,
    SessionGroupInstance,
    SessionRecordInstance,
    SessionRecordList,
    ArticleCode,
    PanelId,
    Subscriber,
    StockId,
    OnSucessCallback, 
    ProductsCollection, 
    SearchWrapperList,
    SearchWrapper,
    WorkerInstance, 
    WorkersCollection,
    WorkerEmail, 
    WorkerName, 
    WorkerPhone,
    SessionRecordsCollection,
    SessionId, 
    SessionDate,
    ExtraData, 
    AddSessionWorker,
    SessionGroupName,
    SessionGroupCollection,
    SessionGroupId,
    SessionWorkersCollection,
    SessionWorkerId,
    SessionsCollection,
    SessionInstance,
    SessionWorkerInstance,
    LoadWrapper, StoreEvent, ExportedTable, ExportWrapper, ImportWrapper, EStoreEvents, EStoreEvent,
}
